name: Selenium

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v4

    - name: npm ci
      run: npm ci

    - name: install Firefox
      run: sudo apt install firefox
    
    - name: npm run wdio
      run: npm run wdio
