name: Selenium

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Chromium
      run: sudo apt-get install chromium-browser

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v4

    - name: npm ci
      run: npm ci
    
    - name: npm run wdio wdio-github.conf.js
      run: npm run wdio wdio-github.conf.js
